language: ruby
cache:
  apt: true
  directories:
    - vendor/bundle
    - $HOME/.cache/pip
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
install:
  - bundle install --path vendor/bundle --jobs=3 --retry=3
