language: ruby
cache:
  apt: true
  directories:
    - vendor/bundle
    - $HOME/.cache/pip
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-1.7.27
  - jruby
  - truffleruby
before_install:
  - type bundle || gem install bundler --version '~> 1.0'
install:
  - bundle install --path vendor/bundle --jobs=3 --retry=3
